services:
  npm:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./npm/data:/data
      - ./npm/letsencrypt:/etc/letsencrypt
    networks:
      - home_net

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - PORTAINER_HTTP_ENABLED=true
      - PORTAINER_HTTPS_ENABLED=false
    volumes:
      # Sync time with host
      - /etc/localtime:/etc/localtime:ro
      # Crucial: This gives Portainer access to control Docker
      - /var/run/docker.sock:/var/run/docker.sock
      # Persistent storage for your admin password and settings
      - portainer_data:/data
    ports:
      - "9000:9000"

volumes:
  portainer_data:

networks:
  home_net:
    driver: bridge
